### ISSUE TITLE
Cleanup - paint folder not deleted

### ISSUE THREAD

**Issue by Fuel44** [Robertsmania/iRacingEquanimityPaint#6]
Probably due to read only sub files?

**Comment by Robertsmania** [comment]
Fixed in 538bf34591ee08d656c47f8486ca2424f5393e91

**Comment by Robertsmania** [comment]
I also added a couple more calls to CleanUp - when the application starts and when you use the 'R' key to reload.  It seems like if you want the paints folder removed, you want it gone in those conditions as well as when the application quits or iRacing disconnects.

Personally, I'm not keen on the wholesale deletion of the paints folder - that seems like a heavy operation and might remove user paints or other files that they dont realize will be removed. 

There are also conditions where iRacing may have a file open when you try to remove the folder, in which case it will show you a message that the file could not be removed because another application is accessing it - in that case I dont think there is anything we can do but move on.

**Comment by Fuel44** [comment]
Originally, I just thought that it was the easiest way to cleanup the paint folder to avoid bloating. I suppose a more elegant approach to accomplishing this would be to delete only the files that the app processed in that session? However, it seems that anyone that is using this app would not be concerned with inadvertently deleting paint files. And, they can now opt out.
