### ISSUE TITLE
Re-run action creates a window for iRacing paint to be applied to a car or two

### ISSUE THREAD

**Issue by Fuel44** [Robertsmania/iRacingEquanimityPaint#7]
I believe this may be due to the re-run calling the CleanUp routine? When I remove the call, and let the painting process delete the files, the issue seems to never happen. I suppose that it shouldn't delete the paints folder when in-session, other than when irEP is closed?

**Comment by Robertsmania** [comment]
I have not been able to repro what you describe, but could imagine how its possible since there is a 2 second delay after the paint folder is deleted by CleanUp() before the textures are copied in OnSessionInfo().

I removed the call to CleanUp() from the set of instructions when the 'R' key is detected.

Hopefully fixed in 0aab770edcc69c8f875f5f84971536832cccf966
