### ISSUE TITLE
PaintCommon\random_selection - old files

### ISSUE THREAD

**Issue by Fuel44** [Robertsmania/iRacingEquanimityPaint#8]
The PaintCommon\random_selection folder should be cleaned up each time, to deal with files that only pertain to a previous run (e.g., car_num from previous run will override car_ file for the current run that doesn't want a car_num override.

**Comment by Robertsmania** [comment]
Okay, this will operate independently of the DeletePaintsFolder option and just be a behavior when RandomMode is true.

It will be a little awkward with QuitAfterCopy since that exits the program directly but I think I see where I could put a call to clean up the random_selection files before that happens.

**Comment by Robertsmania** [comment]
The most elegant way to deal with this seems to be to clean out the random selection folder before the new files are copied.  When the program quits, the previous run riles will still be in that folder (which I think is desirable, in case you wanted to do anything with them or confirm what they were).  But they are cleaned out every time before the new random files are copied into random_selection.

**Comment by Robertsmania** [comment]
Fixed in f5f1e7754c6af804e9f37a1a33aa193f02e69ec6
